
# 打印所有可用信息
```rust
use std::error::Error;
use std::io::{stderr, Write};
fn print_error(mut err: &dyn Error) {
    let _ = writeln!(stderr(), "error:{}", err);
    while let Some(source) = err.source() {
        let _ = writeln!(stderr(), "caused by : {}", source);
        err = source;
    }
}
```
err.source()：
1. 返回导致err的底层错误，err1.source（）----> err2
2. 如果err2是根本原因，则err2.source（）为None

# 减少编译后代码的大小
```toml
....
[profile.debug]
panic = "abort"

[profile.release]
panic = "abort"
```

#  error抽象
所有error都可以转换成GenericError，但不再能准确表达错误的含义
```rust
type GenericError=Box<dyn std::error::Error + Send +Sync+'static>;
type GenericResult<T>=Result<T,GenericError>;
```

# `error.downcast_ref::<Err>`
专门处理某一类型的错误
```rust
use std::io;

fn main() {
    let _ = testForDowncast_ref();
}
type GenericError = Box<dyn std::error::Error + Send + Sync + 'static>;
type GenericResult<T> = Result<T, GenericError>;
fn compile_project() -> GenericResult<()> {
    let io_error = io::Error::new(io::ErrorKind::Other, "time out");
    return Err(GenericError::from(io_error));
}
fn testForDowncast_ref() -> GenericResult<()> {
    match compile_project() {
        Ok(()) => return Ok(()),
        Err(err) => {
            if let Some(msg) = err.downcast_ref::<io::Error>() {
                println!("{}",msg.to_string());
            }
            return Err(err);
        }
    }
}
//time out
```

# 自定义错误类型
```rust
#[derive(Debug, Clone)]
pub struct JsonError {
    pub message: String,
    pub line: usize,
    pub column: usize,
}
impl fmt::Display for JsonError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{} ({}:{})", self.message, self.line, self.column)
    }
}
//使用error trait的默认方法即可
impl std::error::Error for JsonError {}
```
